apiVersion: "nuclio.io/v1"
kind: NuclioFunction
metadata:
  name: hello-nuclio
  labels:
    nuclio.io/project-name: hello-nuclio
spec:
  description: "Showcases unstructured logging and a structured response."
  handler: "main:Handler"
  runtime: golang
  minReplicas: 1
  maxReplicas: 1
  triggers:
    nuclio-demo:
      class: ""
      kind: http
      maxWorkers: 8
      attributes:
        ingresses:
          "0":
            host: nuclio.demo
            paths:
              - /hello-nuclio
  version: 1
  alias: latest
  serviceType: NodePort

